Script started on 2020-10-26 15:17:11-0500
]0;omarzanji@DESKTOP-IQ1U2QB: /mnt/c/Users/ozanj/Desktop/Code/programming_classes/operating_systems/hw4[01;32momarzanji@DESKTOP-IQ1U2QB[00m:[01;34m/mnt/c/Users/ozanj/Desktop/Code/prrogramming_classes/operating_systems/hw4[00m$ git pullclone git@githhub.com:patrickspafford/article-generator.git[A[Cpush origin master[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ccommit -m "buggy text generation working!"[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[8Padd .
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls[Kgit add .commit -m "bugggy text generation working!"[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cpush origin master[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cclone git@github.com:patrickspafford/article-generator.git[A[Cpull[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K./Omar_Barazanji_ 4
Banner id: 903862963
Philosopher 0 is thinking
Philosopher 1 is thinking
Philosopher 2 is thinking
Philosopher 3 is thinking
Philosopher 4 is thinking
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 4 is hungry 
Philosopher 1 is hungry 
Philosopher 0 is hungry 
Philosopher 2 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 4 is hungry 
Philosopher 1 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
^C
]0;omarzanji@DESKTOP-IQ1U2QB: /mnt/c/Users/ozanj/Desktop/Code/programming_classes/operating_systems/hw4[01;32momarzanji@DESKTOP-IQ1U2QB[00m:[01;34m/mnt/c/Users/ozanj/Desktop/Code/prrogramming_classes/operating_systems/hw4[00m$ exit
exit

Script done on 2020-10-26 15:17:33-0500
